POST http://localhost:3001/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test44@test.com",
  "password": "test",
  "userName": "tester"
}

###
POST http://localhost:3001/api/v1/auth/signin
Content-Type: application/json

{
  "email": "test44@test.com",
  "password": "test"
}

###
POST http://localhost:3001/api/v1/auth/signout

###
GET http://localhost:3001/api/v1/todos
