name: backend-test

on:
  pull_request:
    branches: ["main"]
    paths:
      - "todo-backend/**"

env:
  DOCKER_IMAGE: ${{ secrets.REGISTRY }}/${{ secrets.BACKEND_IMAGE_NAME }}:latest
  NAME: todo-backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd todo-backend && yarn install && npm run test
