name: tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'todo-backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'todo-backend/**'
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : cd todo-backend && yarn install && npm run test

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # buildx 설정      
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2 # build-push-action 사용
        with:
          context: ./todo-backend
          file: ./todo-backend/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest
          cache-from: type=gha # Guthub Actions 용 캐시
          cache-to: type=gha,mode=max
          
          
